### PR TITLE
use go modules and remove xtgo/uuid in place of google/uuid

### PR DESCRIPTION
**Pull request by dillonstreator**
## Description of the change

> remove vendoring in place of go modules and drop `xtgo/uuid` for `google/uuid`

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by pallabmaiti** [comment]
Hey @dillonstreator,
We are doing this enhancement in this [PR](https://github.com/rudderlabs/analytics-go/pull/11). We will release it soon. Unfortunately, we can't merge this PR.

**Comment by dillonstreator** [comment]
> Hey @dillonstreator, We are doing this enhancement in this [PR](https://github.com/rudderlabs/analytics-go/pull/11). We will release it soon. Unfortunately, we can't merge this PR.

All good I just noticed #11
I'm curious - what is the reason for using `xtgo/uuid` over one of the more ubiquitous package like `google/uuid`?

**Comment by pallabmaiti** [comment]
Segment was using it. And this repo was forked from them. We hadn't fetched the latest code for a while.

**Comment by dillonstreator** [comment]
close in favor of #11

**Comment by pallabmaiti** [comment]
Hey @dillonstreator, we have released a new version of Go v4.0.0.

**Pull request closed without merging**
